package client.bean.chat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import client.bean.chat.dao.ChatFriendBean;
import client.bean.chat.dao.ChatFriendGroupBean;
import client.bean.chat.dao.ChatMessageBean;
import client.bean.chat.dao.ChatViewBean;
import client.bean.chat.dao.TestBean;
import client.bean.chat.FileBean;
import client.bean.chat.PhotoBean;
import client.bean.chat.SoundBean;
import client.bean.chat.TextBean;

import client.bean.chat.dao.ChatFriendBeanDao;
import client.bean.chat.dao.ChatFriendGroupBeanDao;
import client.bean.chat.dao.ChatMessageBeanDao;
import client.bean.chat.dao.ChatViewBeanDao;
import client.bean.chat.dao.TestBeanDao;
import client.bean.chat.FileBeanDao;
import client.bean.chat.PhotoBeanDao;
import client.bean.chat.SoundBeanDao;
import client.bean.chat.TextBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatFriendBeanDaoConfig;
    private final DaoConfig chatFriendGroupBeanDaoConfig;
    private final DaoConfig chatMessageBeanDaoConfig;
    private final DaoConfig chatViewBeanDaoConfig;
    private final DaoConfig testBeanDaoConfig;
    private final DaoConfig fileBeanDaoConfig;
    private final DaoConfig photoBeanDaoConfig;
    private final DaoConfig soundBeanDaoConfig;
    private final DaoConfig textBeanDaoConfig;

    private final ChatFriendBeanDao chatFriendBeanDao;
    private final ChatFriendGroupBeanDao chatFriendGroupBeanDao;
    private final ChatMessageBeanDao chatMessageBeanDao;
    private final ChatViewBeanDao chatViewBeanDao;
    private final TestBeanDao testBeanDao;
    private final FileBeanDao fileBeanDao;
    private final PhotoBeanDao photoBeanDao;
    private final SoundBeanDao soundBeanDao;
    private final TextBeanDao textBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatFriendBeanDaoConfig = daoConfigMap.get(ChatFriendBeanDao.class).clone();
        chatFriendBeanDaoConfig.initIdentityScope(type);

        chatFriendGroupBeanDaoConfig = daoConfigMap.get(ChatFriendGroupBeanDao.class).clone();
        chatFriendGroupBeanDaoConfig.initIdentityScope(type);

        chatMessageBeanDaoConfig = daoConfigMap.get(ChatMessageBeanDao.class).clone();
        chatMessageBeanDaoConfig.initIdentityScope(type);

        chatViewBeanDaoConfig = daoConfigMap.get(ChatViewBeanDao.class).clone();
        chatViewBeanDaoConfig.initIdentityScope(type);

        testBeanDaoConfig = daoConfigMap.get(TestBeanDao.class).clone();
        testBeanDaoConfig.initIdentityScope(type);

        fileBeanDaoConfig = daoConfigMap.get(FileBeanDao.class).clone();
        fileBeanDaoConfig.initIdentityScope(type);

        photoBeanDaoConfig = daoConfigMap.get(PhotoBeanDao.class).clone();
        photoBeanDaoConfig.initIdentityScope(type);

        soundBeanDaoConfig = daoConfigMap.get(SoundBeanDao.class).clone();
        soundBeanDaoConfig.initIdentityScope(type);

        textBeanDaoConfig = daoConfigMap.get(TextBeanDao.class).clone();
        textBeanDaoConfig.initIdentityScope(type);

        chatFriendBeanDao = new ChatFriendBeanDao(chatFriendBeanDaoConfig, this);
        chatFriendGroupBeanDao = new ChatFriendGroupBeanDao(chatFriendGroupBeanDaoConfig, this);
        chatMessageBeanDao = new ChatMessageBeanDao(chatMessageBeanDaoConfig, this);
        chatViewBeanDao = new ChatViewBeanDao(chatViewBeanDaoConfig, this);
        testBeanDao = new TestBeanDao(testBeanDaoConfig, this);
        fileBeanDao = new FileBeanDao(fileBeanDaoConfig, this);
        photoBeanDao = new PhotoBeanDao(photoBeanDaoConfig, this);
        soundBeanDao = new SoundBeanDao(soundBeanDaoConfig, this);
        textBeanDao = new TextBeanDao(textBeanDaoConfig, this);

        registerDao(ChatFriendBean.class, chatFriendBeanDao);
        registerDao(ChatFriendGroupBean.class, chatFriendGroupBeanDao);
        registerDao(ChatMessageBean.class, chatMessageBeanDao);
        registerDao(ChatViewBean.class, chatViewBeanDao);
        registerDao(TestBean.class, testBeanDao);
        registerDao(FileBean.class, fileBeanDao);
        registerDao(PhotoBean.class, photoBeanDao);
        registerDao(SoundBean.class, soundBeanDao);
        registerDao(TextBean.class, textBeanDao);
    }
    
    public void clear() {
        chatFriendBeanDaoConfig.clearIdentityScope();
        chatFriendGroupBeanDaoConfig.clearIdentityScope();
        chatMessageBeanDaoConfig.clearIdentityScope();
        chatViewBeanDaoConfig.clearIdentityScope();
        testBeanDaoConfig.clearIdentityScope();
        fileBeanDaoConfig.clearIdentityScope();
        photoBeanDaoConfig.clearIdentityScope();
        soundBeanDaoConfig.clearIdentityScope();
        textBeanDaoConfig.clearIdentityScope();
    }

    public ChatFriendBeanDao getChatFriendBeanDao() {
        return chatFriendBeanDao;
    }

    public ChatFriendGroupBeanDao getChatFriendGroupBeanDao() {
        return chatFriendGroupBeanDao;
    }

    public ChatMessageBeanDao getChatMessageBeanDao() {
        return chatMessageBeanDao;
    }

    public ChatViewBeanDao getChatViewBeanDao() {
        return chatViewBeanDao;
    }

    public TestBeanDao getTestBeanDao() {
        return testBeanDao;
    }

    public FileBeanDao getFileBeanDao() {
        return fileBeanDao;
    }

    public PhotoBeanDao getPhotoBeanDao() {
        return photoBeanDao;
    }

    public SoundBeanDao getSoundBeanDao() {
        return soundBeanDao;
    }

    public TextBeanDao getTextBeanDao() {
        return textBeanDao;
    }

}
