package haoshi.com.shop.bean.chat;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import haoshi.com.shop.bean.chat.dao.DaoSession;

import haoshi.com.shop.bean.chat.dao.ChatFriendBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "MESSAGE_BEAN".
*/
public class MessageBeanDao extends AbstractDao<MessageBean, String> {

    public static final String TABLENAME = "MESSAGE_BEAN";

    /**
     * Properties of entity MessageBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Time = new Property(1, long.class, "time", false, "TIME");
        public final static Property Type = new Property(2, int.class, "type", false, "TYPE");
        public final static Property Num = new Property(3, int.class, "num", false, "NUM");
        public final static Property From = new Property(4, int.class, "from", false, "FROM");
        public final static Property Sign = new Property(5, String.class, "sign", false, "SIGN");
    }

    private DaoSession daoSession;


    public MessageBeanDao(DaoConfig config) {
        super(config);
    }
    
    public MessageBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"MESSAGE_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TIME\" INTEGER NOT NULL ," + // 1: time
                "\"TYPE\" INTEGER NOT NULL ," + // 2: type
                "\"NUM\" INTEGER NOT NULL ," + // 3: num
                "\"FROM\" INTEGER NOT NULL ," + // 4: from
                "\"SIGN\" TEXT UNIQUE );"); // 5: sign
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"MESSAGE_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, MessageBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getTime());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getNum());
        stmt.bindLong(5, entity.getFrom());
 
        String sign = entity.getSign();
        if (sign != null) {
            stmt.bindString(6, sign);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, MessageBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
        stmt.bindLong(2, entity.getTime());
        stmt.bindLong(3, entity.getType());
        stmt.bindLong(4, entity.getNum());
        stmt.bindLong(5, entity.getFrom());
 
        String sign = entity.getSign();
        if (sign != null) {
            stmt.bindString(6, sign);
        }
    }

    @Override
    protected final void attachEntity(MessageBean entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public MessageBean readEntity(Cursor cursor, int offset) {
        MessageBean entity = new MessageBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.getLong(offset + 1), // time
            cursor.getInt(offset + 2), // type
            cursor.getInt(offset + 3), // num
            cursor.getInt(offset + 4), // from
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // sign
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, MessageBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTime(cursor.getLong(offset + 1));
        entity.setType(cursor.getInt(offset + 2));
        entity.setNum(cursor.getInt(offset + 3));
        entity.setFrom(cursor.getInt(offset + 4));
        entity.setSign(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(MessageBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(MessageBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(MessageBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getSoundBeanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T1", daoSession.getTextBeanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T2", daoSession.getFileBeanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T3", daoSession.getPhotoBeanDao().getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T4", daoSession.getChatFriendBeanDao().getAllColumns());
            builder.append(" FROM MESSAGE_BEAN T");
            builder.append(" LEFT JOIN SOUND_BEAN T0 ON T.\"SIGN\"=T0.\"SIGN\"");
            builder.append(" LEFT JOIN TEXT_BEAN T1 ON T.\"SIGN\"=T1.\"SIGN\"");
            builder.append(" LEFT JOIN FILE_BEAN T2 ON T.\"SIGN\"=T2.\"SIGN\"");
            builder.append(" LEFT JOIN PHOTO_BEAN T3 ON T.\"SIGN\"=T3.\"SIGN\"");
            builder.append(" LEFT JOIN CHAT_FRIEND_BEAN T4 ON T.\"ID\"=T4.\"FID\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected MessageBean loadCurrentDeep(Cursor cursor, boolean lock) {
        MessageBean entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        SoundBean soundBean = loadCurrentOther(daoSession.getSoundBeanDao(), cursor, offset);
        entity.setSoundBean(soundBean);
        offset += daoSession.getSoundBeanDao().getAllColumns().length;

        TextBean textBean = loadCurrentOther(daoSession.getTextBeanDao(), cursor, offset);
        entity.setTextBean(textBean);
        offset += daoSession.getTextBeanDao().getAllColumns().length;

        FileBean fileBean = loadCurrentOther(daoSession.getFileBeanDao(), cursor, offset);
        entity.setFileBean(fileBean);
        offset += daoSession.getFileBeanDao().getAllColumns().length;

        PhotoBean photoBean = loadCurrentOther(daoSession.getPhotoBeanDao(), cursor, offset);
        entity.setPhotoBean(photoBean);
        offset += daoSession.getPhotoBeanDao().getAllColumns().length;

        ChatFriendBean fUser = loadCurrentOther(daoSession.getChatFriendBeanDao(), cursor, offset);
        entity.setFUser(fUser);

        return entity;    
    }

    public MessageBean loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<MessageBean> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<MessageBean> list = new ArrayList<MessageBean>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<MessageBean> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<MessageBean> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
