package haoshi.com.shop.bean.chat.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_FLOCK_BEAN".
*/
public class ChatFlockBeanDao extends AbstractDao<ChatFlockBean, String> {

    public static final String TABLENAME = "CHAT_FLOCK_BEAN";

    /**
     * Properties of entity ChatFlockBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Groupid = new Property(0, String.class, "groupid", true, "GROUPID");
        public final static Property Grouplogo = new Property(1, String.class, "grouplogo", false, "GROUPLOGO");
        public final static Property Groupname = new Property(2, String.class, "groupname", false, "GROUPNAME");
        public final static Property Nums = new Property(3, String.class, "nums", false, "NUMS");
    }


    public ChatFlockBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ChatFlockBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_FLOCK_BEAN\" (" + //
                "\"GROUPID\" TEXT PRIMARY KEY NOT NULL ," + // 0: groupid
                "\"GROUPLOGO\" TEXT," + // 1: grouplogo
                "\"GROUPNAME\" TEXT," + // 2: groupname
                "\"NUMS\" TEXT);"); // 3: nums
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_FLOCK_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChatFlockBean entity) {
        stmt.clearBindings();
 
        String groupid = entity.getGroupid();
        if (groupid != null) {
            stmt.bindString(1, groupid);
        }
 
        String grouplogo = entity.getGrouplogo();
        if (grouplogo != null) {
            stmt.bindString(2, grouplogo);
        }
 
        String groupname = entity.getGroupname();
        if (groupname != null) {
            stmt.bindString(3, groupname);
        }
 
        String nums = entity.getNums();
        if (nums != null) {
            stmt.bindString(4, nums);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChatFlockBean entity) {
        stmt.clearBindings();
 
        String groupid = entity.getGroupid();
        if (groupid != null) {
            stmt.bindString(1, groupid);
        }
 
        String grouplogo = entity.getGrouplogo();
        if (grouplogo != null) {
            stmt.bindString(2, grouplogo);
        }
 
        String groupname = entity.getGroupname();
        if (groupname != null) {
            stmt.bindString(3, groupname);
        }
 
        String nums = entity.getNums();
        if (nums != null) {
            stmt.bindString(4, nums);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public ChatFlockBean readEntity(Cursor cursor, int offset) {
        ChatFlockBean entity = new ChatFlockBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // groupid
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // grouplogo
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // groupname
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // nums
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChatFlockBean entity, int offset) {
        entity.setGroupid(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGrouplogo(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setGroupname(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setNums(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final String updateKeyAfterInsert(ChatFlockBean entity, long rowId) {
        return entity.getGroupid();
    }
    
    @Override
    public String getKey(ChatFlockBean entity) {
        if(entity != null) {
            return entity.getGroupid();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChatFlockBean entity) {
        return entity.getGroupid() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
