package haoshi.com.shop.bean.chat.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import haoshi.com.shop.bean.chat.dao.ChatFlockBean;
import haoshi.com.shop.bean.chat.dao.ChatFriendBean;
import haoshi.com.shop.bean.chat.dao.ChatFriendGroupBean;
import haoshi.com.shop.bean.chat.dao.ChatViewBean;
import haoshi.com.shop.bean.chat.FileBean;
import haoshi.com.shop.bean.chat.MessageBean;
import haoshi.com.shop.bean.chat.PhotoBean;
import haoshi.com.shop.bean.chat.SoundBean;
import haoshi.com.shop.bean.chat.TextBean;
import haoshi.com.shop.bean.chat.dao.SendBean;

import haoshi.com.shop.bean.chat.dao.ChatFlockBeanDao;
import haoshi.com.shop.bean.chat.dao.ChatFriendBeanDao;
import haoshi.com.shop.bean.chat.dao.ChatFriendGroupBeanDao;
import haoshi.com.shop.bean.chat.dao.ChatViewBeanDao;
import haoshi.com.shop.bean.chat.FileBeanDao;
import haoshi.com.shop.bean.chat.MessageBeanDao;
import haoshi.com.shop.bean.chat.PhotoBeanDao;
import haoshi.com.shop.bean.chat.SoundBeanDao;
import haoshi.com.shop.bean.chat.TextBeanDao;
import haoshi.com.shop.bean.chat.dao.SendBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatFlockBeanDaoConfig;
    private final DaoConfig chatFriendBeanDaoConfig;
    private final DaoConfig chatFriendGroupBeanDaoConfig;
    private final DaoConfig chatViewBeanDaoConfig;
    private final DaoConfig fileBeanDaoConfig;
    private final DaoConfig messageBeanDaoConfig;
    private final DaoConfig photoBeanDaoConfig;
    private final DaoConfig soundBeanDaoConfig;
    private final DaoConfig textBeanDaoConfig;
    private final DaoConfig sendBeanDaoConfig;

    private final ChatFlockBeanDao chatFlockBeanDao;
    private final ChatFriendBeanDao chatFriendBeanDao;
    private final ChatFriendGroupBeanDao chatFriendGroupBeanDao;
    private final ChatViewBeanDao chatViewBeanDao;
    private final FileBeanDao fileBeanDao;
    private final MessageBeanDao messageBeanDao;
    private final PhotoBeanDao photoBeanDao;
    private final SoundBeanDao soundBeanDao;
    private final TextBeanDao textBeanDao;
    private final SendBeanDao sendBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatFlockBeanDaoConfig = daoConfigMap.get(ChatFlockBeanDao.class).clone();
        chatFlockBeanDaoConfig.initIdentityScope(type);

        chatFriendBeanDaoConfig = daoConfigMap.get(ChatFriendBeanDao.class).clone();
        chatFriendBeanDaoConfig.initIdentityScope(type);

        chatFriendGroupBeanDaoConfig = daoConfigMap.get(ChatFriendGroupBeanDao.class).clone();
        chatFriendGroupBeanDaoConfig.initIdentityScope(type);

        chatViewBeanDaoConfig = daoConfigMap.get(ChatViewBeanDao.class).clone();
        chatViewBeanDaoConfig.initIdentityScope(type);

        fileBeanDaoConfig = daoConfigMap.get(FileBeanDao.class).clone();
        fileBeanDaoConfig.initIdentityScope(type);

        messageBeanDaoConfig = daoConfigMap.get(MessageBeanDao.class).clone();
        messageBeanDaoConfig.initIdentityScope(type);

        photoBeanDaoConfig = daoConfigMap.get(PhotoBeanDao.class).clone();
        photoBeanDaoConfig.initIdentityScope(type);

        soundBeanDaoConfig = daoConfigMap.get(SoundBeanDao.class).clone();
        soundBeanDaoConfig.initIdentityScope(type);

        textBeanDaoConfig = daoConfigMap.get(TextBeanDao.class).clone();
        textBeanDaoConfig.initIdentityScope(type);

        sendBeanDaoConfig = daoConfigMap.get(SendBeanDao.class).clone();
        sendBeanDaoConfig.initIdentityScope(type);

        chatFlockBeanDao = new ChatFlockBeanDao(chatFlockBeanDaoConfig, this);
        chatFriendBeanDao = new ChatFriendBeanDao(chatFriendBeanDaoConfig, this);
        chatFriendGroupBeanDao = new ChatFriendGroupBeanDao(chatFriendGroupBeanDaoConfig, this);
        chatViewBeanDao = new ChatViewBeanDao(chatViewBeanDaoConfig, this);
        fileBeanDao = new FileBeanDao(fileBeanDaoConfig, this);
        messageBeanDao = new MessageBeanDao(messageBeanDaoConfig, this);
        photoBeanDao = new PhotoBeanDao(photoBeanDaoConfig, this);
        soundBeanDao = new SoundBeanDao(soundBeanDaoConfig, this);
        textBeanDao = new TextBeanDao(textBeanDaoConfig, this);
        sendBeanDao = new SendBeanDao(sendBeanDaoConfig, this);

        registerDao(ChatFlockBean.class, chatFlockBeanDao);
        registerDao(ChatFriendBean.class, chatFriendBeanDao);
        registerDao(ChatFriendGroupBean.class, chatFriendGroupBeanDao);
        registerDao(ChatViewBean.class, chatViewBeanDao);
        registerDao(FileBean.class, fileBeanDao);
        registerDao(MessageBean.class, messageBeanDao);
        registerDao(PhotoBean.class, photoBeanDao);
        registerDao(SoundBean.class, soundBeanDao);
        registerDao(TextBean.class, textBeanDao);
        registerDao(SendBean.class, sendBeanDao);
    }
    
    public void clear() {
        chatFlockBeanDaoConfig.clearIdentityScope();
        chatFriendBeanDaoConfig.clearIdentityScope();
        chatFriendGroupBeanDaoConfig.clearIdentityScope();
        chatViewBeanDaoConfig.clearIdentityScope();
        fileBeanDaoConfig.clearIdentityScope();
        messageBeanDaoConfig.clearIdentityScope();
        photoBeanDaoConfig.clearIdentityScope();
        soundBeanDaoConfig.clearIdentityScope();
        textBeanDaoConfig.clearIdentityScope();
        sendBeanDaoConfig.clearIdentityScope();
    }

    public ChatFlockBeanDao getChatFlockBeanDao() {
        return chatFlockBeanDao;
    }

    public ChatFriendBeanDao getChatFriendBeanDao() {
        return chatFriendBeanDao;
    }

    public ChatFriendGroupBeanDao getChatFriendGroupBeanDao() {
        return chatFriendGroupBeanDao;
    }

    public ChatViewBeanDao getChatViewBeanDao() {
        return chatViewBeanDao;
    }

    public FileBeanDao getFileBeanDao() {
        return fileBeanDao;
    }

    public MessageBeanDao getMessageBeanDao() {
        return messageBeanDao;
    }

    public PhotoBeanDao getPhotoBeanDao() {
        return photoBeanDao;
    }

    public SoundBeanDao getSoundBeanDao() {
        return soundBeanDao;
    }

    public TextBeanDao getTextBeanDao() {
        return textBeanDao;
    }

    public SendBeanDao getSendBeanDao() {
        return sendBeanDao;
    }

}
